### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Parivalavan** [wolfgangmm/atom-existdb#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [existdb](https://github.com/wolfgangmm/atom-existdb) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'find' of undefined

```
At C:\Users\pari.EXETERPM\.atom\packages\existdb\lib\tree-view.coffee:131

TypeError: Cannot read property 'find' of undefined
    at TreeView.module.exports.TreeView.TreeView.getSelected (/packages/existdb/lib/tree-view.coffee:131:18)
    at EXistTreeView.module.exports.EXistTreeView.uploadSelected (/packages/existdb/lib/existdb-tree-view.coffee:393:38)
    at /packages/existdb/lib/existdb-tree-view.coffee:94:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:10.2.0 existdb:create-configuration-for-selected (span.name.icon.icon-file-directory)
     -1:50.7.0 intentions:highlight (input.hidden-input)
  2x -1:50.3.0 core:paste (input.hidden-input)
     -1:49.4.0 core:undo (input.hidden-input)
     -1:48.6.0 core:paste (input.hidden-input)
     -1:42.9.0 core:move-right (input.hidden-input)
     -1:42.2.0 editor:select-to-end-of-word (input.hidden-input)
     -1:41.8.0 intentions:highlight (input.hidden-input)
  2x -1:41.6.0 editor:select-to-end-of-word (input.hidden-input)
  2x -1:40.8.0 core:backspace (input.hidden-input)
     -1:38.7.0 intentions:highlight (input.hidden-input)
     -1:38.4.0 core:save (input.hidden-input)
     -1:12.8.0 intentions:highlight (input.hidden-input)
     -1:12.6.0 core:save (input.hidden-input)
     -0:39.3.0 existdb:upload-selected (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
busy-signal 1.3.0 
existdb 0.5.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.0 
linter-ui-default 1.2.1 
```

**Comment by joewiz** [comment]
Please provide steps to reproduce!
