### ISSUE TITLE
Uncaught TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/atom-existdb#23]
[Enter steps to reproduce:]

1. Clone atom-existdb (current develop), `apm install`, `apm link`
2. Start atom, install atom-editor server side app
3. File > New
4. Edit > Select Grammar > XQuery
5. Cmd-alt-i to bring up import module dialog - which succeeds (and is great!)
6. Select console module from list of available modules - which triggers this error

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [existdb](https://github.com/wolfgangmm/atom-existdb) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'line' of undefined

```
At /Users/joe/workspace/atom-existdb/lib/xq-prolog.js:22

TypeError: Cannot read property 'line' of undefined
    at XQueryProlog.addImport (/Users/joe/workspace/atom-existdb/lib/xq-prolog.js:22:79)
    at ImportsView.confirm (/Users/joe/workspace/atom-existdb/lib/imports.js:51:16)
    at SelectListView.confirmSelection (/Users/joe/workspace/atom-existdb/node_modules/atom-select-list/src/select-list-view.js:303:20)
    at HTMLDivElement.core:confirm (/Users/joe/workspace/atom-existdb/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:36.9.0 snippets:expand (atom-text-editor.editor.is-focused)
  2x -0:35.6.0 core:move-down (input.hidden-input)
     -0:31.9.0 intentions:highlight (input.hidden-input)
     -0:30.7.0 existdb:import-module (input.hidden-input)
     -0:26.4.0 core:backspace (input.hidden-input)
     -0:25.6.0 core:confirm (input.hidden-input)
     -0:14.8.0 core:move-down (input.hidden-input)
     -0:14.4.0 editor:newline (input.hidden-input)
     -0:13.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:13.3.0 snippets:expand (atom-text-editor.editor.is-focused)
  4x -0:10.9.0 core:move-up (input.hidden-input)
     -0:09.7.0 core:move-down (input.hidden-input)
  2x -0:09.4.0 editor:newline (input.hidden-input)
     -0:08.4.0 core:move-up (input.hidden-input)
     -0:06.6.0 existdb:import-module (input.hidden-input)
     -0:04.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
existdb 0.5.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.0 
```

**Comment by joewiz** [comment]
Confirmed, the error is gone. Thank you!
