### ISSUE TITLE
Uncaught Error: Invalid XML: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>

### ISSUE THREAD

**Issue by duncdrum** [wolfgangmm/atom-existdb#25]
[Enter steps to reproduce:]

1. run xquery in atom that runs fine in exide

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [existdb](https://github.com/wolfgangmm/atom-existdb) package 0.6.0

### Stack Trace

Uncaught Error: Invalid XML: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>

```
At /Users/HALmob/.atom/packages/existdb/node_modules/jquery/dist/jquery.js:253

Error: Invalid XML: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
    at Function.error (/packages/existdb/node_modules/jquery/dist/jquery.js:253:9)
    at Function.jQuery.parseXML (/packages/existdb/node_modules/jquery/dist/jquery.js:7983:10)
    at Request._callback (/packages/existdb/lib/existdb.coffee:146:30)
    at Request.self.callback (/packages/atom-beautify/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/atom-beautify/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/atom-beautify/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -3:16.9.0 core:save (input.hidden-input)
  3x -3:14.7.0 core:move-left (input.hidden-input)
  2x -3:13.2.0 core:save (input.hidden-input)
  2x -3:00.9.0 core:backspace (input.hidden-input)
     -2:41.6.0 core:save (input.hidden-input)
     -2:32.5.0 core:delete (input.hidden-input)
     -2:31.6.0 core:save (input.hidden-input)
     -1:16.5.0 find-and-replace:show (input.hidden-input)
  2x -0:55.1.0 core:backspace (input.hidden-input)
     -0:49 core:save (input.hidden-input)
     -0:47.5.0 find-and-replace:show (input.hidden-input)
     -0:38.5.0 core:save (input.hidden-input)
     -0:35.8.0 existdb:run (input.hidden-input)
     -0:29.6.0 find-and-replace:show (input.hidden-input)
     -0:17.7.0 core:save (input.hidden-input)
  2x -0:15.6.0 existdb:run (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-live-server 2.1.2 
autocomplete-xml 0.9.4 
build 0.68.0 
build-sassc 0.8.2 
busy 0.7.0 
busy-signal 1.4.3 
emmet 2.4.3 
existdb 0.6.0 
file-icons 2.1.12 
htmlhint 1.1.4 
hyperclick 0.1.5 
intentions 1.1.5 
language-jsoniq 1.8.0 
linter 2.2.0 
linter-autocomplete-jing 0.8.2 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
logo-file-icons 1.12.0 
markdown-image-helper 1.0.4 
merge-conflicts 1.4.5 
minimap 4.29.7 
open-html-in-browser 0.2.0 
pigments 0.40.2 
project-manager 3.3.5 
tablr 1.8.3 
todo-show 2.1.0 
wordcount 2.10.4 
xml-common-schemata 0.0.3 
xml-tools 0.2.1 
Zen 0.18.0 
zotero-citations 0.19.1 
```

**Comment by duncdrum** [comment]
I dropped the code that created the error, will open new issue when I encounter it again

**Comment by duncdrum** [comment]
The only URIs are namespaces, and none is even close to reaching any limits any limits. Oxygen, eXide all produce the correct output so no clue whats going on here. 
This now happened twice with completely unrelated queries
